# Generated by Django 4.1.7 on 2023-03-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='Project_id', primary_key=True, serialize=False)),
                ('wiki_article', models.CharField(max_length=500, null=True)),
                ('tar_lang', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.IntegerField()),
                ('original_sentence', models.CharField(max_length=2000, null=True)),
                ('translated_ssentence', models.CharField(max_length=2000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki_app.project')),
            ],
        ),
    ]
