# Generated by Django 4.1.7 on 2023-03-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
