# Generated by Django 4.1.7 on 2023-03-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='translated_ssentence',
            new_name='translated_sentence',
        ),
    ]
